import type { Campaign, PlatformMetrics } from '@/types'

export const campaigns: Campaign[] = [
  {
    id: 'cmp1',
    name: 'Healthy Cooking — Prospecting',
    platform: 'meta',
    status: 'active',
    spend: 6820,
    leads: 38,
    cpl: 179,
    appointments: 12,
    sales: 4,
    revenue: 19200,
    roas: 2.82,
    clientId: 'c1',
  },
  {
    id: 'cmp2',
    name: 'Healthy Cooking — Recipes UGC',
    platform: 'tiktok',
    status: 'learning',
    spend: 5660,
    leads: 23,
    cpl: 246,
    appointments: 6,
    sales: 2,
    revenue: 9600,
    roas: 1.7,
    clientId: 'c1',
  },
  {
    id: 'cmp3',
    name: 'FitLife — Transformation Challenge',
    platform: 'meta',
    status: 'active',
    spend: 5980,
    leads: 31,
    cpl: 193,
    appointments: 7,
    sales: 2,
    revenue: 11400,
    roas: 1.91,
    clientId: 'c2',
  },
  {
    id: 'cmp4',
    name: 'FitLife — Retargeting Warm',
    platform: 'meta',
    status: 'paused',
    spend: 3660,
    leads: 13,
    cpl: 281,
    appointments: 2,
    sales: 0,
    revenue: 0,
    roas: 0,
    clientId: 'c2',
  },
  {
    id: 'cmp5',
    name: 'Casa Bella — Lead Gen',
    platform: 'tiktok',
    status: 'active',
    spend: 3210,
    leads: 16,
    cpl: 201,
    appointments: 3,
    sales: 1,
    revenue: 14200,
    roas: 4.42,
    clientId: 'c3',
  },
  {
    id: 'cmp6',
    name: 'Casa Bella — Open House',
    platform: 'google',
    status: 'learning',
    spend: 2000,
    leads: 6,
    cpl: 333,
    appointments: 1,
    sales: 0,
    revenue: 0,
    roas: 0,
    clientId: 'c3',
  },
]

export const platformMetrics: PlatformMetrics[] = [
  {
    platform: 'meta',
    spend: 16460,
    leads: 82,
    cpl: 201,
    appointments: 21,
    sales: 6,
    revenue: 30600,
  },
  {
    platform: 'tiktok',
    spend: 8870,
    leads: 39,
    cpl: 227,
    appointments: 9,
    sales: 3,
    revenue: 23800,
  },
]
