import type { Lead } from '@/types'
import { daysAgo, hoursAgo, inDays, inHours, minutesAgo } from './time'
import { DEMO_WORKSPACE_ID } from './workspace'

export const leads: Lead[] = [
  {
    id: 'l1',
    workspaceId: DEMO_WORKSPACE_ID,
    leadType: 'sales',
    isDemo: true,
    name: 'María González',
    phone: '+34 612 445 782',
    email: 'maria.gonzalez@email.com',
    source: 'meta',
    campaignId: 'cmp1',
    campaignName: 'Healthy Cooking — Prospecting',
    score: 92,
    temperature: 'hot',
    stage: 'new_lead',
    assignedToId: 'u3',
    potentialValue: 4800,
    createdAt: minutesAgo(8),
    lastContactAt: null,
    nextFollowUpAt: inHours(1),
    nextAction: 'Llamar en los próximos 10 minutos',
    attribution: {
      platform: 'meta',
      campaign: 'Healthy Cooking — Prospecting',
      adSet: 'Lookalike 1% — Buyers',
      ad: 'Recipe carousel v3',
      creative: 'carousel_recipes_a',
    },
    clientId: 'c1',
  },
  {
    id: 'l2',
    workspaceId: DEMO_WORKSPACE_ID,
    leadType: 'sales',
    isDemo: true,
    name: 'Roberto Sánchez',
    phone: '+34 645 118 903',
    email: 'roberto.s@email.com',
    source: 'tiktok',
    campaignId: 'cmp2',
    campaignName: 'Healthy Cooking — Recipes UGC',
    score: 74,
    temperature: 'warm',
    stage: 'contacted',
    assignedToId: 'u4',
    potentialValue: 3200,
    createdAt: hoursAgo(5),
    lastContactAt: hoursAgo(2),
    nextFollowUpAt: inHours(20),
    nextAction: 'Enviar precios por WhatsApp',
    attribution: {
      platform: 'tiktok',
      campaign: 'Healthy Cooking — Recipes UGC',
      adSet: 'Interest — Home cooking',
      ad: 'UGC chef testimonial',
      creative: 'ugc_chef_02',
    },
    clientId: 'c1',
  },
  {
    id: 'l3',
    workspaceId: DEMO_WORKSPACE_ID,
    leadType: 'sales',
    isDemo: true,
    name: 'Lucía Martín',
    phone: '+34 699 552 014',
    email: 'lucia.martin@email.com',
    source: 'meta',
    campaignId: 'cmp3',
    campaignName: 'FitLife — Transformation Challenge',
    score: 88,
    temperature: 'hot',
    stage: 'appointment',
    assignedToId: 'u2',
    potentialValue: 2600,
    createdAt: daysAgo(1),
    lastContactAt: hoursAgo(6),
    nextFollowUpAt: inDays(1),
    nextAction: 'Confirmar la cita de mañana a las 5 p. m.',
    attribution: {
      platform: 'meta',
      campaign: 'FitLife — Transformation Challenge',
      adSet: 'Broad — Women 25-45',
      ad: 'Before/after reel',
      creative: 'reel_transformation_1',
    },
    clientId: 'c2',
  },
  {
    id: 'l4',
    workspaceId: DEMO_WORKSPACE_ID,
    leadType: 'sales',
    isDemo: true,
    name: 'Andrés Vega',
    phone: '+34 611 908 342',
    email: 'andres.vega@email.com',
    source: 'tiktok',
    campaignId: 'cmp5',
    campaignName: 'Casa Bella — Lead Gen',
    score: 38,
    temperature: 'cold',
    stage: 'new_lead',
    assignedToId: 'u4',
    potentialValue: 12000,
    createdAt: minutesAgo(42),
    lastContactAt: null,
    nextFollowUpAt: inHours(3),
    nextAction: 'Calificar presupuesto',
    attribution: {
      platform: 'tiktok',
      campaign: 'Casa Bella — Lead Gen',
      adSet: 'Geo — Madrid centro',
      ad: 'Apartment tour',
      creative: 'tour_madrid_a',
    },
    clientId: 'c3',
  },
  {
    id: 'l5',
    workspaceId: DEMO_WORKSPACE_ID,
    leadType: 'sales',
    isDemo: true,
    name: 'Carmen Ortega',
    phone: '+34 622 774 561',
    email: 'carmen.ortega@email.com',
    source: 'meta',
    campaignId: 'cmp1',
    campaignName: 'Healthy Cooking — Prospecting',
    score: 81,
    temperature: 'hot',
    stage: 'interested',
    assignedToId: 'u3',
    potentialValue: 4800,
    createdAt: daysAgo(2),
    lastContactAt: hoursAgo(20),
    nextFollowUpAt: inHours(4),
    nextAction: 'Enviar video demo del producto',
    attribution: {
      platform: 'meta',
      campaign: 'Healthy Cooking — Prospecting',
      adSet: 'Lookalike 1% — Buyers',
      ad: 'Recipe carousel v3',
      creative: 'carousel_recipes_a',
    },
    clientId: 'c1',
  },
  {
    id: 'l6',
    workspaceId: DEMO_WORKSPACE_ID,
    leadType: 'sales',
    isDemo: true,
    name: 'Pablo Herrera',
    phone: '+34 655 231 887',
    email: 'pablo.herrera@email.com',
    source: 'meta',
    campaignId: 'cmp3',
    campaignName: 'FitLife — Transformation Challenge',
    score: 67,
    temperature: 'warm',
    stage: 'contact',
    assignedToId: 'u2',
    potentialValue: 2600,
    createdAt: hoursAgo(9),
    lastContactAt: null,
    nextFollowUpAt: inHours(2),
    nextAction: 'Primer contacto por WhatsApp',
    attribution: {
      platform: 'meta',
      campaign: 'FitLife — Transformation Challenge',
      adSet: 'Broad — Women 25-45',
      ad: 'Before/after reel',
      creative: 'reel_transformation_1',
    },
    clientId: 'c2',
  },
  {
    id: 'l7',
    workspaceId: DEMO_WORKSPACE_ID,
    leadType: 'sales',
    isDemo: true,
    name: 'Elena Ramírez',
    phone: '+34 633 490 125',
    email: 'elena.ramirez@email.com',
    source: 'tiktok',
    campaignId: 'cmp2',
    campaignName: 'Healthy Cooking — Recipes UGC',
    score: 95,
    temperature: 'hot',
    stage: 'sale',
    assignedToId: 'u3',
    potentialValue: 4800,
    createdAt: daysAgo(4),
    lastContactAt: daysAgo(1),
    nextFollowUpAt: null,
    nextAction: 'Llamada de onboarding',
    attribution: {
      platform: 'tiktok',
      campaign: 'Healthy Cooking — Recipes UGC',
      adSet: 'Interest — Home cooking',
      ad: 'UGC chef testimonial',
      creative: 'ugc_chef_02',
    },
    clientId: 'c1',
  },
  {
    id: 'l8',
    workspaceId: DEMO_WORKSPACE_ID,
    leadType: 'sales',
    isDemo: true,
    name: 'Javier Moreno',
    phone: '+34 677 812 340',
    email: 'javier.moreno@email.com',
    source: 'meta',
    campaignId: 'cmp1',
    campaignName: 'Healthy Cooking — Prospecting',
    score: 58,
    temperature: 'warm',
    stage: 'follow_up',
    assignedToId: 'u4',
    potentialValue: 4800,
    createdAt: daysAgo(3),
    lastContactAt: daysAgo(1),
    nextFollowUpAt: inDays(2),
    nextAction: 'Dar seguimiento a la objeción de precio',
    attribution: {
      platform: 'meta',
      campaign: 'Healthy Cooking — Prospecting',
      adSet: 'Retargeting — 30d visitors',
      ad: 'Discount reminder',
      creative: 'static_discount_10',
    },
    clientId: 'c1',
  },
  {
    id: 'l9',
    workspaceId: DEMO_WORKSPACE_ID,
    leadType: 'sales',
    isDemo: true,
    name: 'Sofía Navarro',
    phone: '+34 688 445 019',
    email: 'sofia.navarro@email.com',
    source: 'tiktok',
    campaignId: 'cmp5',
    campaignName: 'Casa Bella — Lead Gen',
    score: 79,
    temperature: 'warm',
    stage: 'appointment',
    assignedToId: 'u2',
    potentialValue: 12000,
    createdAt: daysAgo(2),
    lastContactAt: hoursAgo(30),
    nextFollowUpAt: inDays(1),
    nextAction: 'Visita al inmueble el sábado',
    attribution: {
      platform: 'tiktok',
      campaign: 'Casa Bella — Lead Gen',
      adSet: 'Geo — Madrid centro',
      ad: 'Apartment tour',
      creative: 'tour_madrid_a',
    },
    clientId: 'c3',
  },
  {
    id: 'l10',
    workspaceId: DEMO_WORKSPACE_ID,
    leadType: 'sales',
    isDemo: true,
    name: 'Miguel Castro',
    phone: '+34 699 003 771',
    email: 'miguel.castro@email.com',
    source: 'meta',
    campaignId: 'cmp3',
    campaignName: 'FitLife — Transformation Challenge',
    score: 44,
    temperature: 'cold',
    stage: 'new_lead',
    assignedToId: 'u4',
    potentialValue: 2600,
    createdAt: minutesAgo(23),
    lastContactAt: null,
    nextFollowUpAt: inHours(1),
    nextAction: 'Calificar nivel de interés',
    attribution: {
      platform: 'meta',
      campaign: 'FitLife — Transformation Challenge',
      adSet: 'Broad — Men 25-45',
      ad: 'Gym results reel',
      creative: 'reel_gym_men_1',
    },
    clientId: 'c2',
  },
  {
    id: 'l11',
    workspaceId: DEMO_WORKSPACE_ID,
    leadType: 'sales',
    isDemo: true,
    name: 'Isabel Ruiz',
    phone: '+34 611 552 908',
    email: 'isabel.ruiz@email.com',
    source: 'meta',
    campaignId: 'cmp1',
    campaignName: 'Healthy Cooking — Prospecting',
    score: 86,
    temperature: 'hot',
    stage: 'contacted',
    assignedToId: 'u3',
    potentialValue: 4800,
    createdAt: hoursAgo(3),
    lastContactAt: hoursAgo(1),
    nextFollowUpAt: inHours(6),
    nextAction: 'Agendar sesión de degustación',
    attribution: {
      platform: 'meta',
      campaign: 'Healthy Cooking — Prospecting',
      adSet: 'Lookalike 1% — Buyers',
      ad: 'Recipe carousel v3',
      creative: 'carousel_recipes_a',
    },
    clientId: 'c1',
  },
  {
    id: 'l12',
    workspaceId: DEMO_WORKSPACE_ID,
    leadType: 'sales',
    isDemo: true,
    name: 'Tomás Gil',
    phone: '+34 655 900 214',
    email: 'tomas.gil@email.com',
    source: 'tiktok',
    campaignId: 'cmp2',
    campaignName: 'Healthy Cooking — Recipes UGC',
    score: 62,
    temperature: 'warm',
    stage: 'interested',
    assignedToId: 'u4',
    potentialValue: 3200,
    createdAt: daysAgo(1),
    lastContactAt: hoursAgo(10),
    nextFollowUpAt: inHours(8),
    nextAction: 'Responder dudas sobre ingredientes',
    attribution: {
      platform: 'tiktok',
      campaign: 'Healthy Cooking — Recipes UGC',
      adSet: 'Interest — Home cooking',
      ad: 'UGC chef testimonial',
      creative: 'ugc_chef_02',
    },
    clientId: 'c1',
  },
  {
    id: 'l13',
    workspaceId: DEMO_WORKSPACE_ID,
    leadType: 'sales',
    isDemo: true,
    name: 'Natalia Prieto',
    phone: '+34 633 118 552',
    email: 'natalia.prieto@email.com',
    source: 'google',
    campaignId: 'cmp6',
    campaignName: 'Casa Bella — Open House',
    score: 71,
    temperature: 'warm',
    stage: 'contact',
    assignedToId: 'u2',
    potentialValue: 12000,
    createdAt: hoursAgo(14),
    lastContactAt: null,
    nextFollowUpAt: inHours(2),
    nextAction: 'Llamar para confirmar interés',
    attribution: {
      platform: 'google',
      campaign: 'Casa Bella — Open House',
      adSet: 'Search — Piso Madrid',
      ad: 'Open house RSA',
      creative: 'rsa_openhouse',
    },
    clientId: 'c3',
  },
  {
    id: 'l14',
    workspaceId: DEMO_WORKSPACE_ID,
    leadType: 'sales',
    isDemo: true,
    name: 'David Campos',
    phone: '+34 688 774 100',
    email: 'david.campos@email.com',
    source: 'meta',
    campaignId: 'cmp1',
    campaignName: 'Healthy Cooking — Prospecting',
    score: 90,
    temperature: 'hot',
    stage: 'sale',
    assignedToId: 'u2',
    potentialValue: 4800,
    createdAt: daysAgo(5),
    lastContactAt: daysAgo(2),
    nextFollowUpAt: null,
    nextAction: 'Pedir testimonio',
    attribution: {
      platform: 'meta',
      campaign: 'Healthy Cooking — Prospecting',
      adSet: 'Lookalike 1% — Buyers',
      ad: 'Recipe carousel v3',
      creative: 'carousel_recipes_a',
    },
    clientId: 'c1',
  },
]
